image: docker:latest
services:
  - docker:dind
stages:
  - build
#   - deploy

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA" .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA"
    - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA" "$CI_REGISTRY_IMAGE"
    - docker push "$CI_REGISTRY_IMAGE"

# .deploy: &deploy
#   image: docker.io/egeneralov/tkh
#   stage: deploy
#   tags:
#     - kubernetes
#   script:
#     - set -ex
#     - ls -lah
#     - export RELEASE_NAME="$CI_ENVIRONMENT_SLUG-$CI_PROJECT_NAME"
#     - export HELM_SETS="--set image.repository=$CI_REGISTRY_IMAGE --set image.tag=$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA"
#     - export HELM_OPTS="${RELEASE_NAME} .helm --namespace $CI_ENVIRONMENT_SLUG ${HELM_SETS} --wait"
#     - export
#     - (helm install --name ${HELM_OPTS} || helm upgrade ${HELM_OPTS} ) || ( helm history --max 2 ${RELEASE_NAME} | head -n 2 | tail -n 1 | awk '{print $1}' | xargs helm rollback ${RELEASE_NAME} )
# 
# 
# deploy:
#   variables:
#     NAME: $CI_ENVIRONMENT_SLUG-$CI_PROJECT_NAME
#   environment:
#     name: $CI_ENVIRONMENT_SLUG-$CI_PROJECT_NAME
#   <<: *deploy
#   only:
#     - master

